name: Databricks CI/CD

on:
  push:
    branches:
      - main

jobs:

  validate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Validate Python
        run: |
          python -m py_compile notebooks/*.py

  update-databricks-repo:
    needs: validate

    runs-on: ubuntu-latest

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:

      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Verify Connection
        run: databricks workspace ls /

      - name: Update Databricks Repo
        run: |
         databricks repos update 4172731679657168 --branch main
